IG_RUNTIME_TABLES = (
    "management_igclient",
    "management_igclientstageevent",
    "management_igconversationsignal",
    "management_igdeal",
    "management_igdealitem",
    "management_igfollowuptask",
    "management_igmetaeventlog",
    "management_igbotnotification",
    "management_igbotnotificationaudit",
    "management_instagrambotlog",
    "management_instagrambotmessage",
    "management_instagrambotprocessedmessage",
    "management_instagrambotrawevent",
    "management_instagrambotsettings",
)
