# Generated by Django 6.1 on 2026-09-30 00:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewvote_innodb_canary'),
        ('storefront', '0099_publish_veteran_fund_stage_three_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Твоя ідея. Наш кастом.', max_length=120)),
                ('rules_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSubmissionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='campaign_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='campaign_rules_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='review',
            name='cons',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='review',
            name='is_incentivized_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='kind',
            field=models.CharField(choices=[('review', 'Відгук'), ('comment', 'Коментар')], default='review', max_length=12),
        ),
        migrations.AddField(
            model_name='review',
            name='pros',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='review',
            name='story_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='submission_identity',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ціле число 1-5.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка'),
        ),
        migrations.AddField(
            model_name='review',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reviews.reviewcampaign'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'submission_identity', 'kind'), name='review_product_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='review_rating_range'),
        ),
    ]
