# Generated by Django 5.2.11 on 2026-07-17 17:14

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_order_checkout_idempotency_key'),
        ('storefront', '0086_marketplace_feed_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('reference', models.CharField(default=orders.models._generate_payment_attempt_reference, editable=False, max_length=40, unique=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(max_length=100)),
                ('np_office', models.CharField(max_length=200)),
                ('np_settlement_ref', models.CharField(blank=True, default='', max_length=36)),
                ('np_city_ref', models.CharField(blank=True, default='', max_length=36)),
                ('np_warehouse_ref', models.CharField(blank=True, default='', max_length=36)),
                ('pay_type', models.CharField(choices=[('online_full', 'Онлайн оплата (повна сума)'), ('prepay_200', 'Передплата 200 грн')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Розпочато'), ('processing', 'Оплата в процесі'), ('paid', 'Оплачено'), ('prepaid', 'Внесена передплата'), ('failed', 'Неуспішно'), ('expired', 'Протерміновано'), ('cancelled', 'Скасовано'), ('converted', 'Перетворено на замовлення')], default='initiated', max_length=20)),
                ('cart_snapshot', models.JSONField(default=dict)),
                ('tracking_payload', models.JSONField(blank=True, default=dict)),
                ('payment_history', models.JSONField(blank=True, default=list)),
                ('notification_state', models.JSONField(blank=True, default=dict)),
                ('event_state', models.JSONField(blank=True, default=dict)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monobank_invoice_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('invoice_url', models.URLField(blank=True, default='')),
                ('invoice_payload', models.JSONField(blank=True, default=dict)),
                ('invoice_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_status_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_attempt', to='orders.order')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_attempts', to='storefront.promocode')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-pk'],
                'indexes': [models.Index(fields=['status', '-created'], name='pay_attempt_status_created'), models.Index(fields=['user', '-created'], name='pay_attempt_user_created'), models.Index(fields=['invoice_expires_at'], name='pay_attempt_expiry')],
            },
        ),
    ]
