# Generated by Django 5.2.11 on 2026-07-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0072_managementlead_needs_disambiguation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotDataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('source', models.CharField(choices=[('manual_form', 'Manual form'), ('meta_callback', 'Meta callback')], max_length=24)),
                ('identifier', models.CharField(blank=True, default='', max_length=255)),
                ('normalized_identifier', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('meta_user_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('no_match', 'No matching records'), ('received', 'Received')], default='received', max_length=24)),
                ('deleted_clients_count', models.PositiveIntegerField(default=0)),
                ('deleted_messages_count', models.PositiveIntegerField(default=0)),
                ('deleted_raw_events_count', models.PositiveIntegerField(default=0)),
                ('deleted_logs_count', models.PositiveIntegerField(default=0)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DIRECT_BOT data deletion request',
                'verbose_name_plural': 'DIRECT_BOT data deletion requests',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='bot_del_status_dt'), models.Index(fields=['source', '-created_at'], name='bot_del_source_dt')],
            },
        ),
    ]
