# Generated by Django 5.2.11 on 2026-07-09 11:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0073_botdatadeletionrequest'),
        ('orders', '0047_checkoutcapture'),
        ('storefront', '0080_useraction_site_session_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgConversationSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('price_objection', 'Дорого'), ('prepayment_objection', 'Передоплата'), ('size_concern', 'Розмір'), ('gift', 'На подарунок'), ('self_purchase', 'Для себе'), ('custom_print', 'Кастомний принт'), ('ad_reply', 'Відповідь з реклами'), ('no_reply', 'Не відповідає'), ('checkout_started', 'Checkout started'), ('payment_pending', 'Очікує оплату'), ('paid', 'Оплачено'), ('lost', 'Втрачено'), ('spam', 'Спам'), ('manager_takeover', 'Взяв менеджер'), ('discount_offer', 'Знижка'), ('product_interest', 'Інтерес до товару')], db_index=True, max_length=40)),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'IG conversation signal',
                'verbose_name_plural': 'IG conversation signals',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IgFollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('sent', 'Надіслано'), ('cancelled', 'Скасовано'), ('skipped', 'Пропущено')], db_index=True, default='pending', max_length=16)),
                ('kind', models.CharField(choices=[('qualification', 'Уточнення'), ('payment', 'Нагадування про оплату'), ('thinking', 'Клієнт думає'), ('rescue', 'Rescue offer'), ('final', 'Фінальний офер'), ('manager_task', 'Завдання менеджеру')], db_index=True, default='qualification', max_length=24)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('meta_window_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('message_text', models.TextField(blank=True, default='')),
                ('skip_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IG follow-up',
                'verbose_name_plural': 'IG follow-ups',
                'ordering': ['due_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IgMetaEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=80)),
                ('event_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('disabled', 'Вимкнено'), ('skipped', 'Пропущено'), ('sent', 'Надіслано'), ('failed', 'Помилка')], db_index=True, default='skipped', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'IG Meta event log',
                'verbose_name_plural': 'IG Meta event logs',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='igclient',
            name='buying_readiness',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='igclient',
            name='current_color',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Поточний колір'),
        ),
        migrations.AddField(
            model_name='igclient',
            name='current_product_confidence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Впевненість у товарі'),
        ),
        migrations.AddField(
            model_name='igclient',
            name='current_qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Поточна кількість'),
        ),
        migrations.AddField(
            model_name='igclient',
            name='current_size',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Поточний розмір'),
        ),
        migrations.AddField(
            model_name='igclient',
            name='discount_offered_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='igclient',
            name='followup_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='igclient',
            name='hidden_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='igclient',
            name='hidden_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='igclient',
            name='intent',
            field=models.CharField(choices=[('unknown', 'Невідомо'), ('product', 'Готовий товар'), ('custom_print', 'Кастомний принт'), ('price', 'Ціна'), ('size', 'Розмір'), ('payment', 'Оплата'), ('delivery', 'Доставка'), ('order_status', 'Статус замовлення'), ('support', 'Підтримка'), ('spam', 'Спам')], db_index=True, default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='igclient',
            name='language',
            field=models.CharField(blank=True, db_index=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='igclient',
            name='last_manager_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igclient',
            name='lost_reason',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='igclient',
            name='next_followup_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='igclient',
            name='primary_objection',
            field=models.CharField(choices=[('none', 'Немає'), ('price', 'Дорого'), ('prepayment', 'Передоплата'), ('size', 'Розмір'), ('thinking', 'Подумаю'), ('no_reply', 'Не відповідає'), ('no_buy', 'Не купує'), ('trust', 'Довіра'), ('delivery', 'Доставка'), ('other', 'Інше')], db_index=True, default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='igclient',
            name='sales_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='instagrambotsettings',
            name='meta_feedback_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagrambotsettings',
            name='meta_feedback_test_event_code',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='instagrambotmessage',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('model', 'model'), ('manager', 'manager')], max_length=8),
        ),
        migrations.AddIndex(
            model_name='igclient',
            index=models.Index(fields=['intent', 'stage'], name='ig_client_intent_stage'),
        ),
        migrations.AddIndex(
            model_name='igclient',
            index=models.Index(fields=['hidden_at', '-last_message_at'], name='ig_client_hidden_dt'),
        ),
        migrations.AddIndex(
            model_name='igclient',
            index=models.Index(fields=['next_followup_at'], name='ig_client_next_fu'),
        ),
        migrations.AddField(
            model_name='igconversationsignal',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_signals', to='management.igclient'),
        ),
        migrations.AddField(
            model_name='igconversationsignal',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_signals', to='management.instagrambotmessage'),
        ),
        migrations.AddField(
            model_name='igfollowuptask',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to='management.igclient'),
        ),
        migrations.AddField(
            model_name='igfollowuptask',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_tasks', to='management.igdeal'),
        ),
        migrations.AddField(
            model_name='igfollowuptask',
            name='sent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='management.instagrambotmessage'),
        ),
        migrations.AddField(
            model_name='igmetaeventlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_events', to='management.igclient'),
        ),
        migrations.AddField(
            model_name='igmetaeventlog',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_events', to='management.igdeal'),
        ),
        migrations.AddField(
            model_name='igmetaeventlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ig_meta_events', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='igconversationsignal',
            index=models.Index(fields=['client', '-id'], name='ig_sig_client_id'),
        ),
        migrations.AddIndex(
            model_name='igconversationsignal',
            index=models.Index(fields=['signal_type', '-id'], name='ig_sig_type_id'),
        ),
        migrations.AddIndex(
            model_name='igfollowuptask',
            index=models.Index(fields=['status', 'due_at'], name='ig_fu_status_due'),
        ),
        migrations.AddIndex(
            model_name='igfollowuptask',
            index=models.Index(fields=['client', 'status'], name='ig_fu_client_status'),
        ),
        migrations.AddIndex(
            model_name='igfollowuptask',
            index=models.Index(fields=['kind', 'status'], name='ig_fu_kind_status'),
        ),
        migrations.AddIndex(
            model_name='igmetaeventlog',
            index=models.Index(fields=['event_name', '-id'], name='ig_meta_event_id'),
        ),
        migrations.AddIndex(
            model_name='igmetaeventlog',
            index=models.Index(fields=['status', '-id'], name='ig_meta_status_id'),
        ),
    ]
