# Generated by Django 5.2.11 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0074_ig_sales_automation"),
    ]

    operations = [
        migrations.AddField(
            model_name="igclient",
            name="delivery_error",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="igclient",
            name="delivery_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="igclient",
            name="delivery_graph_code",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="igclient",
            name="delivery_graph_subcode",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="igclient",
            name="delivery_http_code",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="igclient",
            name="delivery_status",
            field=models.CharField(blank=True, choices=[("advanced_access", "Meta не дозволяє відповідь: потрібен Advanced Access"), ("window_closed", "24-годинне вікно Meta закрито"), ("message_request_check", "Перевірте «Запити» в Instagram"), ("send_blocked", "Meta тимчасово або постійно блокує відповідь")], db_index=True, default="", max_length=32),
        ),
    ]
