# Generated by Django 5.2.11 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0075_ig_client_delivery_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="igclient",
            name="automation_lease_token",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="igclient",
            name="automation_lease_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
