# Generated by Django 5.2.11 on 2026-07-10

from django.db import migrations, models


def set_processing_start_for_existing_rows(apps, schema_editor):
    """Give already-running workers one safe reclaim grace period on deploy."""
    from django.utils import timezone

    InstagramBotMessage = apps.get_model("management", "InstagramBotMessage")
    InstagramBotMessage.objects.filter(
        status="processing", processing_started_at__isnull=True
    ).update(processing_started_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0076_ig_client_automation_lease"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagrambotmessage",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(
            set_processing_start_for_existing_rows,
            migrations.RunPython.noop,
        ),
    ]
