# Generated by Django 5.2.11 on 2026-07-22 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0077_instagrambotmessage_processing_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgBotNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, default='generic', max_length=64)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('telegram_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_notifications', to='management.igclient')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ig_notif_status_dt'), models.Index(fields=['client', 'event_type', '-created_at'], name='ig_notif_client_event')],
            },
        ),
    ]
