# Generated by Django 5.2.11 on 2026-07-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0078_igbotnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrambotsettings',
            name='last_gemini_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrambotsettings',
            name='last_gemini_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='instagrambotsettings',
            name='last_gemini_model',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
