# Generated by Django 5.2.11 on 2026-07-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0079_instagrambotsettings_last_gemini_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrambotsettings',
            name='gemini_model',
            field=models.CharField(default='gemini-3.6-flash', max_length=80),
        ),
    ]
