# Generated by Django 5.2.11 on 2026-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0084_geminikeystate_probe_telemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrambotsettings',
            name='last_gemini_candidates_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagrambotsettings',
            name='last_gemini_policy_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='instagrambotsettings',
            name='last_gemini_reasoning_level',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='instagrambotsettings',
            name='last_gemini_reasoning_task',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='instagrambotsettings',
            name='last_gemini_thoughts_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
