# Generated by Django 5.2.11 on 2026-07-23 10:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0085_instagrambotsettings_last_gemini_candidates_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgConversationAnalysisSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(max_length=160, unique=True)),
                ('score_band', models.CharField(choices=[('cold', 'Холодний'), ('exploring', 'Вивчає'), ('qualified', 'Кваліфікований'), ('high_intent', 'Високий намір'), ('checkout', 'Оформлення'), ('paid', 'Оплачено'), ('lost', 'Втрачено'), ('opted_out', 'Відмовився від повідомлень')], db_index=True, max_length=24)),
                ('purchase_probability', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('uncertainties', models.JSONField(blank=True, default=list)),
                ('analysis_model', models.CharField(blank=True, default='rules', max_length=80)),
                ('analysis_prompt_version', models.CharField(blank=True, default='', max_length=40)),
                ('rules_version', models.CharField(blank=True, default='', max_length=40)),
                ('reasoning_task', models.CharField(blank=True, default='', max_length=64)),
                ('trigger', models.CharField(blank=True, db_index=True, default='message', max_length=32)),
                ('analysis_latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_snapshots', to='management.igclient')),
                ('last_analyzed_message', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_snapshots', to='management.instagrambotmessage')),
            ],
            options={
                'verbose_name': 'Знімок аналізу IG-діалогу',
                'verbose_name_plural': 'Знімки аналізу IG-діалогів',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['client', '-id'], name='ig_analysis_client_id'), models.Index(fields=['score_band', '-id'], name='ig_analysis_band_id')],
            },
        ),
    ]
