# Generated by Django 5.2.11 on 2026-07-23 13:09

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models


def backfill_confirmed_payment_truth(apps, schema_editor):
    Deal = apps.get_model("management", "IgDeal")
    confirmed = Deal.objects.filter(
        status__in=("paid", "order_created"),
        payment_status__in=("paid", "prepaid"),
        paid_at__isnull=False,
    )
    for deal in confirmed.iterator():
        deal.payment_truth = "confirmed"
        deal.paid_amount = Decimal("200.00") if deal.pay_type == "prepay_200" else deal.amount
        deal.payment_truth_updated_at = deal.paid_at
        deal.save(update_fields=["payment_truth", "paid_amount", "payment_truth_updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0088_enforce_verified_payment_truth'),
    ]

    operations = [
        migrations.AddField(
            model_name='igdeal',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='igdeal',
            name='payment_truth',
            field=models.CharField(choices=[('unverified', 'Не підтверджено'), ('pending', 'Перевіряється'), ('confirmed', 'Оплату підтверджено'), ('partially_refunded', 'Частково повернено'), ('refunded', 'Повністю повернено'), ('reversed', 'Платіж скасовано банком'), ('failed', 'Оплата не пройшла'), ('cancelled', 'Оплату скасовано')], db_index=True, default='unverified', max_length=24),
        ),
        migrations.AddField(
            model_name='igdeal',
            name='payment_truth_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='igdeal',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='IgPaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=64, unique=True)),
                ('provider', models.CharField(default='monobank', max_length=32)),
                ('source', models.CharField(default='provider', max_length=32)),
                ('invoice_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('provider_status', models.CharField(db_index=True, max_length=32)),
                ('provider_modified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refunded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='UAH', max_length=8)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('payload_digest', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_events', to='management.igclient')),
                ('deal', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_events', to='management.igdeal')),
            ],
            options={
                'ordering': ['-provider_modified_at', '-id'],
                'indexes': [models.Index(fields=['deal', '-received_at'], name='ig_payevt_deal_dt'), models.Index(fields=['provider_status', '-received_at'], name='ig_payevt_status_dt')],
            },
        ),
        migrations.RunPython(backfill_confirmed_payment_truth, migrations.RunPython.noop),
    ]
