# Generated by Django 5.2.11 on 2026-07-23 13:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_payment_projections(apps, schema_editor):
    Deal = apps.get_model("management", "IgDeal")
    Projection = apps.get_model("management", "IgPaymentProjection")
    for deal in Deal.objects.exclude(payment_truth="unverified").iterator():
        Projection.objects.get_or_create(
            deal_id=deal.pk,
            defaults={
                "client_id": deal.client_id,
                "truth": deal.payment_truth,
                "gross_amount": deal.paid_amount or Decimal("0"),
                "refunded_amount": deal.refunded_amount or Decimal("0"),
                "paid_at": deal.paid_at,
                "provider_modified_at": None,
            },
        )


def create_append_only_triggers(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    drop_append_only_triggers(apps, schema_editor)
    if vendor in {"mysql", "mariadb"}:
        schema_editor.execute(
            "CREATE TRIGGER ig_payevt_no_update BEFORE UPDATE ON management_igpaymentevent "
            "FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'IgPaymentEvent is append-only'"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_payevt_no_delete BEFORE DELETE ON management_igpaymentevent "
            "FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'IgPaymentEvent is append-only'"
        )
    elif vendor == "sqlite":
        schema_editor.execute(
            "CREATE TRIGGER ig_payevt_no_update BEFORE UPDATE ON management_igpaymentevent "
            "BEGIN SELECT RAISE(ABORT, 'IgPaymentEvent is append-only'); END"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_payevt_no_delete BEFORE DELETE ON management_igpaymentevent "
            "BEGIN SELECT RAISE(ABORT, 'IgPaymentEvent is append-only'); END"
        )


def drop_append_only_triggers(apps, schema_editor):
    schema_editor.execute("DROP TRIGGER IF EXISTS ig_payevt_no_update")
    schema_editor.execute("DROP TRIGGER IF EXISTS ig_payevt_no_delete")


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('management', '0089_payment_truth_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpaymentevent',
            name='amount_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IgPaymentProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truth', models.CharField(choices=[('unverified', 'Не підтверджено'), ('pending', 'Перевіряється'), ('confirmed', 'Оплату підтверджено'), ('partially_refunded', 'Частково повернено'), ('refunded', 'Повністю повернено'), ('reversed', 'Платіж скасовано банком'), ('failed', 'Оплата не пройшла'), ('cancelled', 'Оплату скасовано')], db_index=True, default='unverified', max_length=24)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_modified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('needs_reconciliation', models.BooleanField(db_index=True, default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_projections', to='management.igclient')),
                ('deal', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_projection', to='management.igdeal')),
                ('last_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projected_by', to='management.igpaymentevent')),
            ],
            options={
                'indexes': [models.Index(fields=['client', '-updated_at'], name='ig_payproj_client_dt'), models.Index(fields=['truth', '-updated_at'], name='ig_payproj_truth_dt')],
            },
        ),
        migrations.RunPython(backfill_payment_projections, migrations.RunPython.noop),
        migrations.RunPython(create_append_only_triggers, drop_append_only_triggers),
    ]
