# Generated by Django 5.2.11 on 2026-07-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0091_ig_runtime_innodb'),
    ]

    operations = [
        migrations.AddField(
            model_name='igbotnotification',
            name='failure_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='igbotnotification',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='igbotnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unknown', 'Delivery unknown'), ('dead_letter', 'Manual review required')], db_index=True, default='pending', max_length=16),
        ),
    ]
