# Generated by Django 5.2.11 on 2026-07-23 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0092_notification_outbox_recovery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='igbotnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unknown', 'Delivery unknown'), ('dead_letter', 'Manual review required'), ('resolved', 'Resolved by operator')], db_index=True, default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='IgBotNotificationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('from_status', models.CharField(max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ig_notification_audits', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='management.igbotnotification')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['notification', '-created_at'], name='ig_notif_audit_dt')],
            },
        ),
    ]
