# Generated by Django 6.1 on 2026-09-08 23:22

import django.db.models.deletion
from django.db import migrations, models


def initialize_control(apps, schema_editor):
    if schema_editor.connection.vendor == "mysql":
        for table in ("management_igjourneytracerefreshcontrol", "management_igjourneytracerefreshjob"):
            with schema_editor.connection.cursor() as cursor:
                cursor.execute("SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s", [table])
                row = cursor.fetchone()
                if row is None:
                    raise RuntimeError("Journey trace refresh table is missing")
                if str(row[0]).casefold() != "innodb":
                    schema_editor.execute(f"ALTER TABLE {schema_editor.quote_name(table)} ENGINE=InnoDB")
                cursor.execute("SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s", [table])
                verified = cursor.fetchone()
                if not verified or str(verified[0]).casefold() != "innodb":
                    raise RuntimeError("Journey trace refresh requires InnoDB")
    apps.get_model("management", "IgJourneyTraceRefreshControl").objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('management', '0208_journey_trace_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgJourneyTraceRefreshControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('activation_watermark', models.PositiveBigIntegerField(default=0)),
                ('scan_cursor', models.PositiveBigIntegerField(default=0)),
                ('repair_cursor', models.PositiveBigIntegerField(default=0)),
                ('repair_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('max_starts_per_hour', models.PositiveSmallIntegerField(default=6)),
                ('budget_started_at', models.DateTimeField(blank=True, null=True)),
                ('budget_starts', models.PositiveSmallIntegerField(default=0)),
                ('lease_token', models.CharField(blank=True, default='', max_length=32)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('max_starts_per_hour__gte', 1), ('max_starts_per_hour__lte', 24)), name='ig_trace_refresh_budget_bound')],
            },
        ),
        migrations.CreateModel(
            name='IgJourneyTraceRefreshJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_watermark', models.PositiveBigIntegerField(default=0)),
                ('reset_floor', models.PositiveBigIntegerField(default=1)),
                ('generation', models.PositiveBigIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('due_at', models.DateTimeField()),
                ('attempted_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('attempted_generation', models.PositiveBigIntegerField(default=0)),
                ('lease_token', models.CharField(blank=True, default='', max_length=32)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('last_reason', models.CharField(blank=True, default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journey_trace_refresh', to='management.igclient')),
                ('last_snapshot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refresh_jobs', to='management.igjourneytracesnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'due_at'], name='ig_trace_refresh_due')],
            },
        ),
        migrations.RunPython(initialize_control, migrations.RunPython.noop),
    ]
