# Generated by Django 5.2.11 on 2026-07-08 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0079_alter_useraction_action_type_coupon_apply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fit_selector_enabled',
            field=models.BooleanField(default=True, help_text='Якщо вимкнено — блок з вибором крою не відображається на сторінці товару.', verbose_name='Показувати селектор крою (класика / оверсай��)'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['site_session', 'action_type'], name='idx_action_site_type'),
        ),
    ]
