# Generated by Django 5.2.11 on 2026-07-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SYSTEM_FEEDS = (
    ("google", "Google Merchant", "uk"),
    ("meta", "Instagram / Meta", "uk"),
    ("rozetka", "Rozetka", "uk"),
    ("kasta", "Kasta", "uk_ru"),
    ("buyme", "BuyMe", "uk"),
    ("prom", "Prom.ua", "uk"),
    ("bezzet", "Bezzet", "uk"),
)


def seed_system_marketplace_feeds(apps, schema_editor):
    MarketplaceFeed = apps.get_model("storefront", "MarketplaceFeed")
    for key, name, language in SYSTEM_FEEDS:
        MarketplaceFeed.objects.get_or_create(
            system_key=key,
            defaults={
                "name": name,
                "slug": key,
                "adapter": key,
                "language": language,
                "is_active": True,
                "is_system": True,
                "rules": {},
            },
        )


def unseed_system_marketplace_feeds(apps, schema_editor):
    MarketplaceFeed = apps.get_model("storefront", "MarketplaceFeed")
    MarketplaceFeed.objects.filter(system_key__in=[key for key, _, _ in SYSTEM_FEEDS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0085_restock_delivery_queue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceFeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Назва")),
                ("slug", models.SlugField(max_length=80, unique=True, verbose_name="Slug")),
                ("system_key", models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name="Системний ключ")),
                ("adapter", models.CharField(choices=[("google", "Google Merchant"), ("meta", "Instagram / Meta"), ("rozetka", "Rozetka"), ("kasta", "Kasta"), ("buyme", "BuyMe"), ("prom", "Prom.ua"), ("bezzet", "Bezzet")], max_length=24, verbose_name="Адаптер")),
                ("language", models.CharField(choices=[("uk", "Українська"), ("ru", "Російська"), ("uk_ru", "Українська та російська")], default="uk", max_length=8, verbose_name="Мова")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активний")),
                ("is_system", models.BooleanField(default=False, verbose_name="Системний")),
                ("description", models.CharField(blank=True, max_length=240, verbose_name="Опис")),
                ("rules", models.JSONField(blank=True, default=dict, verbose_name="Правила")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Створено")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Оновлено")),
                ("created_by", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_marketplace_feeds", to=settings.AUTH_USER_MODEL, verbose_name="Створив")),
                ("parent", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="storefront.marketplacefeed", verbose_name="Батьківський профіль")),
            ],
            options={"verbose_name": "Marketplace фід", "verbose_name_plural": "Marketplace фіди", "ordering": ("name", "pk")},
        ),
        migrations.CreateModel(
            name="MarketplaceFeedProductRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inclusion", models.CharField(choices=[("inherit", "Успадкувати"), ("include", "Включити"), ("exclude", "Виключити")], default="inherit", max_length=12, verbose_name="Включення")),
                ("availability", models.CharField(choices=[("inherit", "Успадкувати"), ("in_stock", "В наявності"), ("out_of_stock", "Немає в наявності")], default="inherit", max_length=12, verbose_name="Наявність")),
                ("quantity", models.PositiveIntegerField(blank=True, null=True, verbose_name="Кількість")),
                ("image_tokens", models.JSONField(blank=True, default=list, verbose_name="Вибрані зображення")),
                ("feed", models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name="product_rules", to="storefront.marketplacefeed", verbose_name="Фід")),
                ("product", models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name="marketplace_feed_rules", to="storefront.product", verbose_name="Товар")),
            ],
            options={"verbose_name": "Правило товару для marketplace фіда", "verbose_name_plural": "Правила товарів для marketplace фідів"},
        ),
        migrations.AddIndex(model_name="marketplacefeed", index=models.Index(fields=["adapter", "is_active"], name="idx_feed_adapter_active")),
        migrations.AddIndex(model_name="marketplacefeed", index=models.Index(fields=["parent", "is_active"], name="idx_feed_parent_active")),
        migrations.AddConstraint(model_name="marketplacefeedproductrule", constraint=models.UniqueConstraint(fields=("feed", "product"), name="uniq_feed_product_rule")),
        migrations.RunPython(seed_system_marketplace_feeds, unseed_system_marketplace_feeds),
    ]
