from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
from decimal import Decimal


class Migration(migrations.Migration):
    dependencies = [('finance', '0018_counterpartycard_obligationsettlement')]

    operations = [
        migrations.CreateModel(name='FundingSource', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(max_length=255)), ('source_type', models.CharField(choices=[('grant','Грант'),('targeted','Целевое финансирование'),('other','Другое')], default='grant', max_length=16)),
            ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)), ('received_at', models.DateField(blank=True, null=True)), ('valid_until', models.DateField(blank=True, null=True)), ('notes', models.TextField(blank=True, default='')), ('is_active', models.BooleanField(default=True)), ('created_at', models.DateTimeField(auto_now_add=True)),
            ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_sources', to='finance.company')), ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_sources', to='finance.project')), ('allowed_categories', models.ManyToManyField(blank=True, related_name='funding_sources', to='finance.category')),
        ], options={'ordering': ['-received_at', 'name']}),
        migrations.CreateModel(name='LedgerClassification', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('ownership_scope', models.CharField(choices=[('business','Бизнес'),('personal','Личное'),('mixed','Смешанное'),('unknown','Не определено')], db_index=True, default='unknown', max_length=16)), ('economic_kind', models.CharField(choices=[('sale','Продажа'),('operating_expense','Операционный расход'),('investment','Инвестиция'),('grant_inflow','Грант'),('internal_transfer','Внутренний перевод'),('owner_draw','Вывод владельцу'),('debt_repayment','Погашение долга'),('expense_refund','Возврат расхода'),('personal_transfer','Личный перевод'),('adjustment','Корректировка'),('unknown','Не классифицировано')], db_index=True, default='unknown', max_length=32)), ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)), ('source', models.CharField(default='manual', max_length=16)), ('note', models.TextField(blank=True, default='')), ('updated_at', models.DateTimeField(auto_now=True)), ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_classification', to='finance.transaction')), ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.CreateModel(name='FundingAllocation', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])), ('allocation_type', models.CharField(choices=[('received','Поступление'),('spent','Расход'),('reserved','Резерв')], default='spent', max_length=16)), ('note', models.TextField(blank=True, default='')), ('created_at', models.DateTimeField(auto_now_add=True)), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.fundingsource')), ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_allocations', to='finance.transaction')),
        ], options={'constraints':[models.UniqueConstraint(fields=('funding_source','transaction','allocation_type'), name='finance_funding_alloc_unique')]}),
        migrations.CreateModel(name='InternalTransferMatch', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('amount', models.DecimalField(decimal_places=2, max_digits=18)), ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)), ('status', models.CharField(choices=[('suggested','Предложено'),('confirmed','Подтверждено'),('rejected','Отклонено')], default='suggested', max_length=16)), ('confirmed_at', models.DateTimeField(blank=True, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_matches', to='finance.company')), ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')), ('destination_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfer_matches', to='finance.transaction')), ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')), ('source_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfer_matches', to='finance.transaction')),
        ], options={'constraints':[models.UniqueConstraint(fields=('source_transaction','destination_transaction'), name='finance_transfer_match_unique')]}),
        migrations.CreateModel(name='BalanceReconciliation', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('as_of', models.DateTimeField()), ('observed_balance', models.DecimalField(decimal_places=2, max_digits=18)), ('calculated_balance', models.DecimalField(decimal_places=2, max_digits=18)), ('delta', models.DecimalField(decimal_places=2, max_digits=18)), ('note', models.TextField(blank=True, default='')), ('created_at', models.DateTimeField(auto_now_add=True)), ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='finance.account')), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.CreateModel(name='ClassificationReview', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('proposal', models.JSONField(default=dict)), ('reason', models.TextField(blank=True, default='')), ('impact', models.JSONField(blank=True, default=dict)), ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)), ('status', models.CharField(choices=[('pending','Ожидает'),('accepted','Принято'),('rejected','Отклонено'),('skipped','Пропущено')], db_index=True, default='pending', max_length=16)), ('reviewed_at', models.DateTimeField(blank=True, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_reviews', to='finance.company')), ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_reviews', to='finance.transaction')),
        ]),
        migrations.CreateModel(name='CounterpartyAlias', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('value', models.CharField(max_length=255)), ('normalized', models.CharField(db_index=True, max_length=255)), ('source', models.CharField(default='manual', max_length=16)), ('is_active', models.BooleanField(default=True)), ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_aliases', to='finance.company')), ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='finance.counterparty')),
        ], options={'constraints':[models.UniqueConstraint(fields=('company','normalized'), name='finance_counterparty_alias_unique')]}),
        migrations.CreateModel(name='ObligationGroup', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(max_length=255)), ('type', models.CharField(choices=[('income','Доход'),('expense','Расход')], default='expense', max_length=12)), ('due_day', models.PositiveSmallIntegerField(blank=True, null=True)), ('role', models.CharField(choices=[('charge','Начисление'),('prepayment','Аванс'),('refund','Возврат')], default='charge', max_length=16)), ('status', models.CharField(choices=[('planned','Планируется'),('partial','Частично'),('paid','Оплачено'),('overdue','Просрочено')], default='planned', max_length=16)), ('forecast_policy', models.JSONField(blank=True, default=dict)), ('notes', models.TextField(blank=True, default='')), ('is_active', models.BooleanField(default=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_groups', to='finance.company')), ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligation_groups', to='finance.counterparty')), ('recurrence_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligation_groups', to='finance.recurrencerule')),
        ]),
        migrations.CreateModel(name='ObligationComponent', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=255)), ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)), ('forecast_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)), ('forecast_policy', models.JSONField(blank=True, default=dict)), ('payment_purpose_template', models.TextField(blank=True, default='')), ('sort_order', models.PositiveIntegerField(default=0)), ('is_active', models.BooleanField(default=True)), ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligation_components', to='finance.category')), ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='finance.obligationgroup')), ('recipient_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligation_components', to='finance.counterpartycard')),
        ], options={'ordering': ['sort_order', 'id']}),
        migrations.CreateModel(name='PaymentIntent', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])), ('currency', models.CharField(default='UAH', max_length=3)), ('purpose', models.TextField(blank=True, default='')), ('comment', models.TextField(blank=True, default='')), ('provider', models.CharField(default='monobank_personal', max_length=32)), ('status', models.CharField(choices=[('draft','Черновик'),('awaiting_confirmation','Ожидает подтверждения'),('submitted','Отправлено'),('detected','Найдено в выписке'),('confirmed','Подтверждено'),('rejected','Отклонено'),('expired','Истекло')], db_index=True, default='draft', max_length=24)), ('idempotency_key', models.CharField(max_length=96, unique=True)), ('provider_reference', models.CharField(blank=True, default='', max_length=128)), ('expires_at', models.DateTimeField(blank=True, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='finance.account')), ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='finance.obligationcomponent')), ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='finance.company')), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='finance.transaction')), ('recipient_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='finance.counterpartycard')),
        ]),
        migrations.CreateModel(name='PaymentIntentEvent', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('from_status', models.CharField(blank=True, default='', max_length=24)), ('to_status', models.CharField(max_length=24)), ('payload', models.JSONField(blank=True, default=dict)), ('created_at', models.DateTimeField(auto_now_add=True)), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='finance.paymentintent'))]),
        migrations.CreateModel(name='ObligationComponentSettlement', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])), ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='finance.obligationcomponent')), ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_allocations', to='finance.obligationsettlement'))], options={'constraints':[models.UniqueConstraint(fields=('settlement','component'), name='finance_component_settlement_unique')]}),
    ]
