# Generated by Django 6.1 on 2026-09-21 13:26

import django.db.models.deletion
from django.db import migrations, models


def seed_counterparty_policies(apps, schema_editor):
    Company = apps.get_model('finance', 'Company')
    Category = apps.get_model('finance', 'Category')
    Counterparty = apps.get_model('finance', 'Counterparty')
    Transaction = apps.get_model('finance', 'Transaction')
    RecurrenceRule = apps.get_model('finance', 'RecurrenceRule')
    Policy = apps.get_model('finance', 'CounterpartyClassificationPolicy')

    for company in Company.objects.all():
        business, _ = Category.objects.get_or_create(
            company_id=company.id, name='Оренда та комуналка — бізнес',
            defaults={'type': 'expense', 'is_system': True},
        )
        housing, _ = Category.objects.get_or_create(
            company_id=company.id, name='Оренда та комуналка — житло',
            defaults={'type': 'expense', 'is_system': True},
        )
        viktor = Counterparty.objects.filter(
            company_id=company.id, name__icontains='виктор викторович',
        ).first()
        if not viktor:
            viktor = Counterparty.objects.filter(
                company_id=company.id, name__icontains='віктор вікторович',
            ).first()
        vlada = Counterparty.objects.filter(
            company_id=company.id, name__iexact='Влада мама',
        ).first()
        if viktor:
            Transaction.objects.filter(company_id=company.id, counterparty_id=viktor.id,
                                       type='expense', category__name__iexact='Оренда').update(category_id=business.id)
            RecurrenceRule.objects.filter(company_id=company.id, template_counterparty_id=viktor.id,
                                          template_type='expense', template_category__name__iexact='Оренда').update(template_category_id=business.id)
            Policy.objects.update_or_create(
                company_id=company.id, counterparty_id=viktor.id,
                defaults={
                    'is_enabled': True, 'transaction_type': 'expense',
                    'category_id': business.id, 'economic_kind': 'operating_expense',
                    'ownership_scope': 'business', 'require_confirmation': False,
                    'prompt': 'Зарахувати оплату Виктору Викторовичу до бізнес-оренди та комуналки?',
                },
            )
        if vlada:
            Transaction.objects.filter(company_id=company.id, counterparty_id=vlada.id,
                                       type='expense', category__name__iexact='Оренда').update(category_id=housing.id)
            RecurrenceRule.objects.filter(company_id=company.id, template_counterparty_id=vlada.id,
                                          template_type='expense', template_category__name__iexact='Оренда').update(template_category_id=housing.id)
            Policy.objects.update_or_create(
                company_id=company.id, counterparty_id=vlada.id,
                defaults={
                    'is_enabled': True, 'transaction_type': 'expense',
                    'category_id': housing.id, 'economic_kind': 'operating_expense',
                    'ownership_scope': 'personal', 'require_confirmation': True,
                    'prompt': 'Це оплата оренди та комуналки за житло?',
                },
            )
        crc = Counterparty.objects.filter(company_id=company.id, name__iexact='CRC').first()
        purchase = Category.objects.filter(
            company_id=company.id, name__iexact='Закупівля товару', type__in=('expense', 'both'),
        ).first()
        if crc and purchase:
            Policy.objects.update_or_create(
                company_id=company.id, counterparty_id=crc.id,
                defaults={
                    'is_enabled': True, 'transaction_type': 'expense',
                    'category_id': purchase.id, 'economic_kind': 'operating_expense',
                    'ownership_scope': 'business', 'require_confirmation': True,
                    'prompt': 'Це закупівля товару або одягу у CRC?',
                },
            )
        viysktorg = Counterparty.objects.filter(company_id=company.id, name__iexact='Miy Viysktorg').first()
        sales = Category.objects.filter(
            company_id=company.id, name__iexact='Продажі', type__in=('income', 'both'),
        ).first()
        if viysktorg and sales:
            Policy.objects.update_or_create(
                company_id=company.id, counterparty_id=viysktorg.id,
                defaults={
                    'is_enabled': True, 'transaction_type': 'income',
                    'category_id': sales.id, 'economic_kind': 'sale',
                    'ownership_scope': 'business', 'require_confirmation': True,
                    'prompt': 'Це надходження від продажу через Miy Viysktorg?',
                },
            )




class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_normalize_finance_categories_and_novapay'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyClassificationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('transaction_type', models.CharField(blank=True, default='', help_text='income/expense or blank for either direction', max_length=12)),
                ('economic_kind', models.CharField(default='unknown', max_length=32)),
                ('ownership_scope', models.CharField(default='unknown', max_length=16)),
                ('require_confirmation', models.BooleanField(default=True)),
                ('prompt', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_classification_policies', to='finance.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_classification_policies', to='finance.company')),
                ('counterparty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification_policy', to='finance.counterparty')),
            ],
            options={
                'verbose_name': 'Політика класифікації контрагента',
                'verbose_name_plural': 'Політики класифікації контрагентів',
            },
        ),
        migrations.RunPython(seed_counterparty_policies, migrations.RunPython.noop),
    ]
